### PR TITLE
Add Json type support

### PR DESCRIPTION
**Pull request by muga**
It allows users to
- Specify the name of Json typed column as 'json_column_name' option.
- Specify Json type as the types of columns declared in 'expanded_columns' option.

### CODE REVIEW

**Comment by muga** [comment]
@civitaspo if you have any concerns to merge this PR into master branch, please let me know:-)

**Comment by civitaspo** [comment]
Oh, sorry, I haven't noticed your p-r.
I do not have any concerns!
Merged.

**Comment by muga** [comment]
ok, thanks.

**Comment by muga** [comment]
@civitaspo Can you release new version of this plugin? It would be appreciated:-)

**Pull request merged**
