### PR TITLE
Support type conversion from floating point numbers to integers

### LINKED ISSUE #32: Adding support for type conversion from floating point numbers to integers
JSON doesn't distinguish integers from floating point numbers. Both of them are number.
There is a confusion around type conversion due to this issue as we got a report at https://github.com/embulk/embulk/issues/775.

For this characteristic of JSON, I think it is reasonable idea to add an automatic conversion from floating point numbers to `long` type in expand_json filter plugin. Even if the source number contains some fraction numbers, rounding it to long is acceptable.

### PR DESCRIPTION
**Pull request by civitaspo**
Fix #32 

@muga @sakama 
Could you review this?

### CODE REVIEW

**Comment by civitaspo** [comment]
openjdk7 and oraclejdk7 tests are failed, but these are not due to this p-r. ref. https://github.com/travis-ci/travis-ci/issues/7884, https://blog.travis-ci.com/2017-08-31-trusty-as-default-status

**Comment by civitaspo** [comment]
Tests will be fixed by https://github.com/civitaspo/embulk-filter-expand_json/pull/34 .

**Comment by sakama** [comment]
@civitaspo Looks good to me. #34 as well.
Thanks for fixing!

**Comment by muga** [comment]
@civitaspo @sakama Sorry to be late but thank you for notifying. This change might be OK for my application.

**Comment by civitaspo** [comment]
Thanks for the reviews!

**Comment by civitaspo** [comment]
released: https://rubygems.org/gems/embulk-filter-expand_json/versions/0.2.1

**Pull request merged**
