### PR TITLE
Release v0.0.6

### PR DESCRIPTION
**Pull request by civitaspo**
- [Add] Support JSON type
  - https://github.com/civitaspo/embulk-filter-expand_json/pull/11
- [Enhancement] Validate json_column_name
  - https://github.com/civitaspo/embulk-filter-expand_json/pull/9

### CODE REVIEW

**Comment by civitaspo** [comment]
@muga v0.0.6 is released. => https://github.com/civitaspo/embulk-filter-expand_json/pull/12, https://rubygems.org/gems/embulk-filter-expand_json/versions/0.0.6
Sorry for the delay of the responce... (recently i'm swamped...) :(

**Comment by uu59** [comment]
Thank you releasing!
But probably you forgot to push v0.0.6 tag?

**Comment by civitaspo** [comment]
Thank you for pointing it out. @uu59 
taged => https://github.com/civitaspo/embulk-filter-expand_json/releases/tag/v0.0.6

`./gradlew gemPush` had better do tagging with `gem release`...

**Comment by muga** [comment]
@civitaspo @uu59 :+1:

**Pull request merged**
