### PR TITLE
Add stop_on_invalid_record option

### PR DESCRIPTION
**Pull request by muga**
Add `stop_on_invalid_record` option
- This option is false by default.
- If the option is false, the plugin skips invalid records if it found them.
- If true, the plugin throws `DataException` if it found an invalid record. CsvParserPlugin also throws same exception.

### CODE REVIEW

**Comment by civitaspo** [comment]
> This option is false by default.

unn... this change breaks backward compatibility... but, this option should be false by default for the  uniformity.

Ok, I release next version as v0.1.0, with CHANGELOG that breaking the backward compatibility.

**Comment by muga** [comment]
Thank you.

> this change breaks backward compatibility... but, this option should be false by default for the uniformity.

Yes, but I believe that's better. And you can change the default value anytime. Up to you:-)

**Comment by civitaspo** [comment]
released! https://rubygems.org/gems/embulk-filter-expand_json/versions/0.1.0

**Comment by muga** [comment]
Thank you for quick work 👍

**Pull request merged**
