### PR TITLE
Fix retrieving unchanged json columns

### PR DESCRIPTION
**Pull request by muga**
In the current impl., the values of Json columns that are not specified as json_column_name are not set to Page objects:-(

### CODE REVIEW

**Comment by civitaspo** [comment]
thx

**Comment by muga** [comment]
thank you 👍

**Comment by civitaspo** [comment]
I will release new version later.
Plz wait for a while.

**Comment by muga** [comment]
Sure. Please do that when you can.

**Comment by civitaspo** [comment]
released https://rubygems.org/gems/embulk-filter-expand_json/versions/0.1.1

**Pull request merged**
