### PR TITLE
Bump up to v0.6.0-SNAPSHOT, change the groupId to "org.embulk", and cleanup GitHub Actions to be consistent

### PR DESCRIPTION
**Pull request by dmikurube**
`embulk-filter-expand_json` has been transferred from @civitaspo.

Along with the transfer, we are :
* Bumping up the version to v0.6.0-SNAPSHOT.
* Changing the groupId to `org.embulk`.
* Removing `.github/FUNDING.yml` because it is now maintained in the community.
* Getting the test CI consistent with other plugins
  * Removing coveralls
    * We may reconsider it later, but we'll apply the same things to all under https://github.com/embulk.
  * Removing configured Webhooks
  * Removing configured branch protection: "Require status checks to pass before merging"
* Adding CODEOWNERS with @embulk/expand-json-maintainers (including @civitaspo)

### CODE REVIEW

**Review by civitaspo — APPROVED** [review]
Thanks a lot!!!!!!

**Comment by dmikurube** [comment]
Thanks!

@vietnguyen-td Could you have a look when you have time?

**Review by vietnguyen-td — APPROVED** [review]
LGTM

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
