### PR TITLE
Support column-based timezone option in expanded columns

### PR DESCRIPTION
**Pull request by muga**
This PR adds column-based timezone option as discuss about it on https://github.com/civitaspo/embulk-filter-expand_json/issues/26. How about it?

It assumes https://github.com/civitaspo/embulk-filter-expand_json/pull/27.

### CODE REVIEW

**Comment by civitaspo** [comment]
Looks Good!

**Comment by civitaspo** [comment]
I will merge this after #27 .(Maybe you need rebasing)

**Comment by muga** [comment]
ok, thank you for reviewing. After #27 is merged, I will do rebase.

**Comment by civitaspo** [comment]
I merged #27, so rebase this 🙏

**Comment by muga** [comment]
Rebased. Please take a look when you have a time.

**Comment by civitaspo** [comment]
(∩´∀｀)∩

**Comment by civitaspo** [comment]
I release a new version. wait for a while.

**Comment by muga** [comment]
Thank you-

**Comment by civitaspo** [comment]
Released https://rubygems.org/gems/embulk-filter-expand_json/versions/0.2.0

**Pull request merged**
