### PR TITLE
Add a validation code to check if json_column_name column is string type

### PR DESCRIPTION
**Pull request by muga**
This fix is to add a validation code for checking if the type of a column specified as json_column_name option is string or not. `setExpandedJsonColumns` method requires that the json column is string type. It's nice to have such type validation.

To add an unit test for this validation, I removed `final` modifier from `schema` field in `TestExpandJsonFilterPlugin` class. But this change might not be bad for us.

### CODE REVIEW

**Comment by civitaspo** [comment]
ship it!

**Comment by civitaspo** [comment]
> this change might not be bad for us

@muga hmm, could you comment on the code the reason the change is needed?
(excuse, I merged already this p-r.)

**Comment by muga** [comment]
@civitaspo Ok, I will do that. To be clarified, the reason why I removed `final` is because my test method requires different `schema` object from `[_c0:string, _c1:string]`, you know. In the future, I think that new additional test methods also will require different schemas. So, this change is reasonable.

**Comment by muga** [comment]
Added comment on the test class. https://github.com/civitaspo/embulk-filter-expand_json/pull/10

Thank you for merging.

**Pull request merged**
